ci: Update changelog check

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -238,8 +238,11 @@ jobs:
           echo "::set-output name=archive::${PLUGIN_ARTIFACT}"
       - name: Check changelog
         run: |
-          if ! grep -q -F "## [${{ steps.metadata.outputs.version }}]" CHANGELOG.md; then
-            echo "Error: The latest (## [${{ steps.metadata.outputs.version }}]) tag was not found in the CHANGELOG.md." 1>&2
+          latest_tag_without_rc=$(echo ${{ steps.metadata.outputs.version }} | sed -r s/-rc\.[0-9]+//)
+
+          if ! grep -q -F "## [${latest_tag_without_rc}]" CHANGELOG.md; then
+            echo "Error: The (## [${latest_tag_without_rc}]) tag was not found in the CHANGELOG.md."
+            echo "Latest tag: ${{ steps.metadata.outputs.version }}" 1>&2
             exit 1
           fi
       - name: Download plugin package
diff --git a/githooks/pre-push b/githooks/pre-push
--- a/githooks/pre-push
+++ b/githooks/pre-push
@@ -1,8 +1,17 @@
 #!/bin/bash
 
+if [ "$(uname)" == "Darwin" ]; then
+    extended_sed="sed -E"      
+else
+	extended_sed="sed -r"
+fi
+
 latest_tag=$(git describe --tags --abbrev=0)
 
-if ! grep -q -F "## [${latest_tag:1}]" CHANGELOG.md; then
-	echo "Error: The latest (## [${latest_tag:1}]) tag was not found in the CHANGELOG.md." 1>&2
+latest_tag_without_rc=$(echo $latest_tag | ${extended_sed} s/-rc\.[0-9]+//)
+
+if ! grep -q -F "## [${latest_tag_without_rc:1}]" CHANGELOG.md; then
+	echo "Error: The (## [${latest_tag_without_rc:1}]) tag was not found in the CHANGELOG.md."
+	echo "Latest tag: ${latest_tag}" 1>&2
 	exit 1
 fi
